/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.tomtom.online.sdk.map;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
